// CS 460 Team 01

public enum SafeState {
    OFF,
    INITIAL_PIN_SETUP,
    SETTING_NEW_PIN,
    NORMAL,
    ADD_NEW_USER,
    CLOSED,
    SETTING_IRIS,
    WAITING_FOR_IRIS,
    LOCKED,
    MASTER_VERIFICATION
}
